#!/bin/sh
echo 'Changing to node-app directory...'
cd ~/node-app
echo 'Git Pull...'
git pull
echo 'Install Production environment for Node-App...'
npm install -—production
echo 'Restart all processes...'
pm2 restart all